import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        // Variables CSS du thème (prioritaires)
        theme: {
          'bg-page': "var(--bg-page, #ffffff)",
          'bg-surface': "var(--bg-surface, #f8fafc)",
          'bg-elevated': "var(--bg-elevated, #f1f5f9)",
          'text-primary': "var(--text-primary, #0f172a)",
          'text-muted': "var(--text-muted, #64748b)",
          'accent': "var(--accent, #2563eb)",
          'accent-hover': "var(--accent-hover, #1d4ed8)",
          'accent-soft': "var(--accent-soft, #eff6ff)",
          'border': "var(--border, #e2e8f0)",
          'border-hover': "var(--border-hover, #cbd5e1)",
          'badge': "var(--badge, #2563eb)",
          'badge-bg': "var(--badge-bg, #eff6ff)",
          'success': "var(--success, #22c55e)",
          'success-bg': "var(--success-bg, #dcfce7)",
          'warning': "var(--warning, #f59e0b)",
          'warning-bg': "var(--warning-bg, #fef3c7)",
          'danger': "var(--danger, #ef4444)",
          'danger-bg': "var(--danger-bg, #fee2e2)",
          'gold': "var(--gold, #f59e0b)",
          'gold-bg': "var(--gold-bg, #fef3c7)",
        },
        // SHAMAR Design System — design-system/01-foundations/colors.txt
        primary: {
          50: "#EEF4FF",
          100: "#DCE7FF",
          200: "#B9CFFF",
          300: "#8FB0FF",
          400: "#5C88FF",
          500: "var(--accent, #356DFF)",
          600: "var(--accent-hover, #1F4DFF)",
          700: "#193ED6",
          800: "#1532A8",
          900: "#0E226E",
        },
        gray: {
          0: "var(--bg-page, #FFFFFF)",
          50: "var(--bg-surface, #F9FAFB)",
          100: "var(--bg-elevated, #F3F4F6)",
          200: "var(--border, #E5E7EB)",
          300: "#D1D5DB",
          400: "#9CA3AF",
          500: "var(--text-muted, #6B7280)",
          600: "#4B5563",
          700: "#374151",
          800: "#1F2937",
          900: "var(--text-primary, #0B1220)",
        },
        success: { 
          500: "var(--success, #22C55E)",
          bg: "var(--success-bg, #dcfce7)",
        },
        warning: { 
          500: "var(--warning, #F59E0B)",
          bg: "var(--warning-bg, #fef3c7)",
        },
        danger: { 
          500: "var(--danger, #EF4444)",
          bg: "var(--danger-bg, #fee2e2)",
        },
        info: { 500: "#06B6D4" },
        brand: {
          vert: "#0E7A5F",
          "vert-fonce": "#0A5C47",
          "vert-clair": "#E6F4EF",
          "bleu-nuit": "#0B1120",
          "bleu-ardoise": "#1E293B",
          "bleu-gris": "#E9EFF3",
          "noir": "#111111",
          "noir-profond": "#0A0A0A",
          anthracite: "#1F2937",
          or: "var(--gold, #D4AF37)",
          "or-clair": "#E6C77A",
          "blanc-casse": "#FAFAFA",
          "gris-clair": "#F1F5F9",
        },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "-apple-system", "Segoe UI", "Roboto", "sans-serif"],
      },
      fontSize: {
        "shamar-h1": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "shamar-h2": ["24px", { lineHeight: "1.25", fontWeight: "600" }],
        "shamar-h3": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "shamar-h4": ["18px", { lineHeight: "1.35", fontWeight: "500" }],
        "shamar-body-lg": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "shamar-body": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "shamar-small": ["12px", { lineHeight: "1.5", fontWeight: "400" }],
        "shamar-caption": ["11px", { lineHeight: "1.4", fontWeight: "400" }],
      },
      spacing: {
        "shamar-4": "4px",
        "shamar-8": "8px",
        "shamar-12": "12px",
        "shamar-16": "16px",
        "shamar-20": "20px",
        "shamar-24": "24px",
        "shamar-32": "32px",
        "shamar-40": "40px",
        "shamar-48": "48px",
        "shamar-64": "64px",
        "shamar-80": "80px",
      },
      borderRadius: {
        "shamar-sm": "6px",
        "shamar-md": "10px",
        "shamar-lg": "14px",
        "shamar-xl": "20px",
      },
      boxShadow: {
        "shamar-soft": "0 2px 8px rgba(0,0,0,0.05)",
        "shamar-medium": "0 6px 16px rgba(0,0,0,0.08)",
        "shamar-large": "0 12px 32px rgba(0,0,0,0.12)",
      },
      maxWidth: {
        "shamar-container": "1280px",
      },
    },
  },
  plugins: [],
};
export default config;
