/**
 * Données réelles et crédibles pour SHAMAR B2B
 * Contexte africain + international
 */

import { randomUUID } from 'crypto';

export interface SeedUser {
  id: string;
  email: string;
  role: 'admin' | 'seller' | 'buyer';
  full_name: string;
  phone: string;
  company_name: string;
  company_address: string;
  country: string;
}

export interface SeedProduct {
  sellerEmail: string;
  name: string;
  description: string;
  price: number;
  currency: 'FCFA' | 'USD' | 'EUR';
  category: string;
  image_url?: string;
  stock_quantity: number;
  min_order_quantity?: number;
  status?: 'active' | 'inactive' | 'sold_out';
}

export const realSeedData = {
  users: [
    // Admin
    {
      id: '550e8400-e29b-41d4-a716-446655440000',
      email: 'admin@shamar.com',
      role: 'admin' as const,
      full_name: 'Kouamé Assoumani',
      phone: '+225 07 12 34 56 78',
      company_name: 'SHAMAR Platform',
      company_address: 'Zone 4, Marcory, Abidjan, Côte d\'Ivoire',
      country: 'CI',
    },

    // Sellers - Coopératives agricoles
    {
      id: '550e8400-e29b-41d4-a716-446655440001',
      email: 'coopcacao@shamar.com',
      role: 'seller' as const,
      full_name: 'Aminata Traoré',
      phone: '+225 05 87 65 43 21',
      company_name: 'Coopérative Cacao San Pedro',
      company_address: 'Boulevard de la République, San Pedro, CI',
      country: 'CI',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440002',
      email: 'anacarde@shamar.com',
      role: 'seller' as const,
      full_name: 'Jean-Baptiste Sossou',
      phone: '+229 96 54 32 10',
      company_name: 'Agri-Bénin Anacarde',
      company_address: 'Avenue du Marché, Parakou, Bénin',
      country: 'BJ',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440003',
      email: 'cafe@shamar.com',
      role: 'seller' as const,
      full_name: 'Youssouf Diallo',
      phone: '+221 77 123 45 67',
      company_name: 'Coopérative Café Kaffrine',
      company_address: 'Route Nationale 1, Kaffrine, Sénégal',
      country: 'SN',
    },

    // Sellers - PME locales
    {
      id: '550e8400-e29b-41d4-a716-446655440004',
      email: 'africatrade@shamar.com',
      role: 'seller' as const,
      full_name: 'Mohammed Diop',
      phone: '+225 01 23 45 67 89',
      company_name: 'Africa Trade Corp',
      company_address: 'Plateau, Avenue Franchet d\'Esperey, Abidjan, CI',
      country: 'CI',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440005',
      email: 'zena@shamar.com',
      role: 'seller' as const,
      full_name: 'Fatou Ndiaye',
      phone: '+221 78 987 65 43',
      company_name: 'Zena Cosmetics',
      company_address: 'Almadies, Route de la Corniche, Dakar, Sénégal',
      country: 'SN',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440006',
      email: 'sodex@shamar.com',
      role: 'seller' as const,
      full_name: 'Koffi Adjo',
      phone: '+229 97 11 22 33',
      company_name: 'Sodex Pro Sourcing',
      company_address: 'Stade de l\'Amitié, Cotonou, Bénin',
      country: 'BJ',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440007',
      email: 'electro@shamar.com',
      role: 'seller' as const,
      full_name: 'Adjoavi Tokpanou',
      phone: '+228 90 11 22 33',
      company_name: 'Electro Plus Afrique',
      company_address: 'Avenue de la République, Lomé, Togo',
      country: 'TG',
    },

    // Sellers - Fournisseurs industriels
    {
      id: '550e8400-e29b-41d4-a716-446655440008',
      email: 'ciments@shamar.com',
      role: 'seller' as const,
      full_name: 'François Kouassi',
      phone: '+225 08 11 22 33 44',
      company_name: 'Ciments du Golfe',
      company_address: 'Zone Industrielle, Abidjan, CI',
      country: 'CI',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440009',
      email: 'metal@shamar.com',
      role: 'seller' as const,
      full_name: 'Ibrahim Konaté',
      phone: '+225 09 88 77 66 55',
      company_name: 'Metal Afrique',
      company_address: 'Yopougon, Abidjan, CI',
      country: 'CI',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440010',
      email: 'textile@shamar.com',
      role: 'seller' as const,
      full_name: 'Awa Sow',
      phone: '+221 70 123 45 67',
      company_name: 'Textiles Dakar',
      company_address: 'Parc Industriel, Dakar, Sénégal',
      country: 'SN',
    },

    // Sellers - Exportateurs / Chine
    {
      id: '550e8400-e29b-41d4-a716-446655440011',
      email: 'sourcingchina@shamar.com',
      role: 'seller' as const,
      full_name: 'Li Wei',
      phone: '+86 138 0013 8000',
      company_name: 'Sino-Afrique Trading',
      company_address: 'Yiwu International Trade City, Zhejiang, Chine',
      country: 'CN',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440012',
      email: 'importexport@shamar.com',
      role: 'seller' as const,
      full_name: 'Marie Dubois',
      phone: '+33 1 23 45 67 89',
      company_name: 'Afro-France Import Export',
      company_address: 'Port de Marseille, France',
      country: 'FR',
    },

    // Sellers - B2C
    {
      id: '550e8400-e29b-41d4-a716-446655440013',
      email: 'fashion@shamar.com',
      role: 'seller' as const,
      full_name: 'Nana Koné',
      phone: '+225 07 55 44 33 22',
      company_name: 'Fashion Boutique Abidjan',
      company_address: 'Cocody, Abidjan, CI',
      country: 'CI',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440014',
      email: 'tech@shamar.com',
      role: 'seller' as const,
      full_name: 'Abdoulaye Ba',
      phone: '+221 77 888 99 00',
      company_name: 'Tech Hub Dakar',
      company_address: 'Point E, Dakar, Sénégal',
      country: 'SN',
    },

    // Buyers - Entreprises
    {
      id: '550e8400-e29b-41d4-a716-446655440015',
      email: 'construction@shamar.com',
      role: 'buyer' as const,
      full_name: 'Bakary Camara',
      phone: '+225 01 44 55 66 77',
      company_name: 'BTP Afrique Ouest',
      company_address: 'Zone 4, Abidjan, CI',
      country: 'CI',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440016',
      email: 'distrib@shamar.com',
      role: 'buyer' as const,
      full_name: 'Kadiatou Touré',
      phone: '+221 78 111 22 33',
      company_name: 'Distribution SA',
      company_address: 'Colobane, Dakar, Sénégal',
      country: 'SN',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440017',
      email: 'restaurant@shamar.com',
      role: 'buyer' as const,
      full_name: 'Ami Sarr',
      phone: '+221 77 222 33 44',
      company_name: 'Restauration Rapide',
      company_address: 'Plateau, Dakar, Sénégal',
      country: 'SN',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440018',
      email: 'retail@shamar.com',
      role: 'buyer' as const,
      full_name: 'Koffi Amegbeto',
      phone: '+228 90 22 33 44',
      company_name: 'Super Marché Lomé',
      company_address: 'Avenue de la Paix, Lomé, Togo',
      country: 'TG',
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440019',
      email: 'industrie@shamar.com',
      role: 'buyer' as const,
      full_name: 'Yao Kouassi',
      phone: '+225 08 33 44 55 66',
      company_name: 'Industrie Locale',
      company_address: 'Yopougon, Abidjan, CI',
      country: 'CI',
    },
  ],

  products: [
    // ========== AGRO & MATIÈRES PREMIÈRES ==========
    // Cacao
    {
      sellerEmail: 'coopcacao@shamar.com',
      name: 'Fèves de cacao séchées premium',
      description: 'Fèves de cacao fermentées et séchées, grade A, origine San Pedro. Teneur en beurre de cacao élevée. Conditionnement en sacs de 50kg. Certifié commerce équitable.',
      price: 1500,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 5000,
      min_order_quantity: 100,
      status: 'active',
    },
    {
      sellerEmail: 'coopcacao@shamar.com',
      name: 'Pâte de cacao transformée',
      description: 'Pâte de cacao pour transformation industrielle, 70% de cacao. Production locale. Livraison possible en containers.',
      price: 2800,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 2000,
      min_order_quantity: 50,
      status: 'active',
    },

    // Anacarde
    {
      sellerEmail: 'anacarde@shamar.com',
      name: 'Noix de cajou crues décortiquées',
      description: 'Anacardes crues décortiquées, calibre W240. Origine Bénin, récolte 2024. Emballage sous vide, sachets de 25kg.',
      price: 4500,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 3000,
      min_order_quantity: 25,
      status: 'active',
    },
    {
      sellerEmail: 'anacarde@shamar.com',
      name: 'Coques de cajou pour extraction',
      description: 'Coques d\'anacarde séchées pour extraction d\'huile de CNSL. Résidu de décorticage, qualité industrielle.',
      price: 150,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 10000,
      min_order_quantity: 100,
      status: 'active',
    },

    // Café
    {
      sellerEmail: 'cafe@shamar.com',
      name: 'Café Arabica lavé',
      description: 'Café Arabica lavé, altitude 1400m, région Kaffrine. Grains verts, grade AA. Conditionnement en sacs de 60kg.',
      price: 3200,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 1500,
      min_order_quantity: 60,
      status: 'active',
    },
    {
      sellerEmail: 'cafe@shamar.com',
      name: 'Café Robusta torréfié',
      description: 'Café Robusta torréfié et moulu, conditionnement 500g. Production locale, saveur intense.',
      price: 2500,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 500,
      min_order_quantity: 20,
      status: 'active',
    },

    // ========== INDUSTRIE & ÉQUIPEMENTS ==========
    // Ciment
    {
      sellerEmail: 'ciments@shamar.com',
      name: 'Ciment CPJ-35 (Portland)',
      description: 'Ciment Portland composé CPJ-35, sacs de 50kg. Norme NF EN 197-1. Production locale, résistance 35 MPa. Livraison en palettes de 48 sacs.',
      price: 7500,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 2000,
      min_order_quantity: 48,
      status: 'active',
    },
    {
      sellerEmail: 'ciments@shamar.com',
      name: 'Ciment CPA-42.5',
      description: 'Ciment Portland Artificiel CPA-42.5, haute résistance. Sacs de 50kg, conditionnement industriel.',
      price: 8500,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 1500,
      min_order_quantity: 48,
      status: 'active',
    },

    // Métaux
    {
      sellerEmail: 'metal@shamar.com',
      name: 'Fers à béton 12mm (Tonne)',
      description: 'Barres d\'armature pour béton armé, diamètre 12mm, longueur 12m. Acier HA E500. Tonne complète (84 barres environ).',
      price: 650000,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 50,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'metal@shamar.com',
      name: 'Tôles ondulées galvanisées',
      description: 'Tôles ondulées galvanisées, épaisseur 0.8mm, largeur 1m, longueur 2.5m. Protection anti-corrosion. Utilisation toiture industrielle et bâtiment.',
      price: 18000,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 300,
      min_order_quantity: 10,
      status: 'active',
    },
    {
      sellerEmail: 'metal@shamar.com',
      name: 'Tubes carrés acier 50x50mm',
      description: 'Profilés acier carrés 50x50x2mm, longueur 6m. Usage structure métallique, charpente, mobilier industriel.',
      price: 45000,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 200,
      min_order_quantity: 5,
      status: 'active',
    },

    // ========== ÉLECTRONIQUE & HIGH-TECH ==========
    {
      sellerEmail: 'electro@shamar.com',
      name: 'Smartphones Android 4G',
      description: 'Smartphones Android 4G, écran 6.1 pouces, 128GB stockage, double SIM. Compatible toutes opérateurs Afrique de l\'Ouest. Garantie 12 mois.',
      price: 85000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 150,
      min_order_quantity: 5,
      status: 'active',
    },
    {
      sellerEmail: 'electro@shamar.com',
      name: 'Tablettes tactiles 10 pouces',
      description: 'Tablettes Android 10 pouces, 64GB, WiFi + 4G optionnel. Usage professionnel et éducation. Compatible stylo.',
      price: 95000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 80,
      min_order_quantity: 3,
      status: 'active',
    },
    {
      sellerEmail: 'tech@shamar.com',
      name: 'Laptops professionnels 15 pouces',
      description: 'Ordinateurs portables 15 pouces, Intel Core i5, 8GB RAM, 256GB SSD. Windows 11 Pro. Garantie constructeur 24 mois.',
      price: 550000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 30,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'electro@shamar.com',
      name: 'Générateurs électriques 5kVA',
      description: 'Groupes électrogènes diesel 5kVA, démarrage électrique, réservoir 25L. Utilisation domestique et PME. Livraison avec huile et filtres.',
      price: 850000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 25,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'electro@shamar.com',
      name: 'Panneaux solaires 300W',
      description: 'Panneaux photovoltaïques monocristallins 300W, certificat CE. Kit complet avec régulateur et câbles. Garantie 25 ans.',
      price: 180000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 50,
      min_order_quantity: 2,
      status: 'active',
    },

    // ========== MODE & TEXTILE ==========
    {
      sellerEmail: 'textile@shamar.com',
      name: 'Tissus Wax premium',
      description: 'Tissus wax imprimés, largeur 120cm, motifs authentiques. Résistance lavage, usage vêtements et décoration. Rouleaux de 50m.',
      price: 8500,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 200,
      min_order_quantity: 10,
      status: 'active',
    },
    {
      sellerEmail: 'textile@shamar.com',
      name: 'Bazin riche premium',
      description: 'Tissu bazin riche, qualité premium, coloris variés. Usage haute couture et événements. Largeur 115cm, rouleaux de 25m.',
      price: 12000,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 100,
      min_order_quantity: 5,
      status: 'active',
    },
    {
      sellerEmail: 'fashion@shamar.com',
      name: 'Boubou traditionnel brodé',
      description: 'Ensembles boubou homme/femme, broderies traditionnelles, tissu bazin. Tailles variées. Confection locale artisanale.',
      price: 45000,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 60,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'fashion@shamar.com',
      name: 'Accessoires mode cuir',
      description: 'Sacs à main et portefeuilles en cuir véritable, fabrication locale. Design moderne et traditionnel. Couleurs disponibles.',
      price: 35000,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 80,
      min_order_quantity: 3,
      status: 'active',
    },

    // ========== IMPORT / EXPORT ==========
    {
      sellerEmail: 'sourcingchina@shamar.com',
      name: 'Équipements électroniques gros volume',
      description: 'Sourcing direct Chine : smartphones, tablettes, accessoires. Quantités importantes, prix compétitifs. Container 20 ou 40 pieds. FOB Yiwu.',
      price: 50000,
      currency: 'USD',
      category: 'Import / Export',
      stock_quantity: 0,
      min_order_quantity: 100,
      status: 'active',
    },
    {
      sellerEmail: 'sourcingchina@shamar.com',
      name: 'Mobilier métallique Chine',
      description: 'Sourcing mobilier métallique professionnel : bureaux, chaises, étagères. Design moderne, finition poudrée. MOQ 100 pièces. Inspection qualité disponible.',
      price: 120,
      currency: 'USD',
      category: 'Import / Export',
      stock_quantity: 0,
      min_order_quantity: 100,
      status: 'active',
    },
    {
      sellerEmail: 'importexport@shamar.com',
      name: 'Services logistique Afrique-Europe',
      description: 'Services de transport et douane pour export Afrique vers Europe. Expertise douanière, documentation, transit. Ports : Dakar, Abidjan, Marseille.',
      price: 2500,
      currency: 'EUR',
      category: 'Import / Export',
      stock_quantity: 0,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'africatrade@shamar.com',
      name: 'Conteneurs maritimes groupage',
      description: 'Service groupage pour import/export Afrique de l\'Ouest. Consolidation cargaisons, transport maritime, dédouanement. Ports : Abidjan, Dakar, Tema.',
      price: 850,
      currency: 'USD',
      category: 'Import / Export',
      stock_quantity: 0,
      min_order_quantity: 1,
      status: 'active',
    },

    // ========== AGRO & MATIÈRES PREMIÈRES - SUITE ==========
    // Huile de palme
    {
      sellerEmail: 'coopcacao@shamar.com',
      name: 'Huile de palme raffinée',
      description: 'Huile de palme raffinée alimentaire, fûts de 20L. Qualité premium, acide oléique élevé. Production locale Côte d\'Ivoire. Livraison en palettes.',
      price: 12000,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 500,
      min_order_quantity: 10,
      status: 'active',
    },
    {
      sellerEmail: 'coopcacao@shamar.com',
      name: 'Noix de coco séchée',
      description: 'Noix de coco déshydratée en copeaux, sachets de 5kg. Usage pâtisserie et cuisine industrielle. Conditionnement sous vide.',
      price: 5500,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 800,
      min_order_quantity: 20,
      status: 'active',
    },
    // Riz
    {
      sellerEmail: 'africatrade@shamar.com',
      name: 'Riz parfumé 1er choix',
      description: 'Riz parfumé long grain, sacs de 50kg. Origine variée, qualité export. Taux de brisure inférieur à 5%. Stock disponible.',
      price: 35000,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 2000,
      min_order_quantity: 20,
      status: 'active',
    },
    {
      sellerEmail: 'africatrade@shamar.com',
      name: 'Riz local brisé',
      description: 'Riz local brisé, sacs de 25kg. Usage restauration collective et transformation. Prix compétitif, livraison immédiate.',
      price: 18000,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 3000,
      min_order_quantity: 25,
      status: 'active',
    },
    // Arachide
    {
      sellerEmail: 'cafe@shamar.com',
      name: 'Arachides décortiquées',
      description: 'Arachides décortiquées, calibre standard, sacs de 50kg. Origine Sénégal. Usage huilerie et consommation directe. Certificat qualité.',
      price: 5500,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 1500,
      min_order_quantity: 50,
      status: 'active',
    },
    {
      sellerEmail: 'cafe@shamar.com',
      name: 'Huile d\'arachide raffinée',
      description: 'Huile d\'arachide raffinée, bouteilles 1L. Production locale Sénégal. Qualité alimentaire, résistance à la cuisson. Cartons de 12 bouteilles.',
      price: 1800,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 1200,
      min_order_quantity: 12,
      status: 'active',
    },
    // Karité
    {
      sellerEmail: 'anacarde@shamar.com',
      name: 'Beurre de karité brut',
      description: 'Beurre de karité non raffiné, pots de 5kg. Extraction traditionnelle, qualité cosmétique. Origine Bénin. Conditionnement hermétique.',
      price: 15000,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 400,
      min_order_quantity: 10,
      status: 'active',
    },
    {
      sellerEmail: 'anacarde@shamar.com',
      name: 'Beurre de karité raffiné',
      description: 'Beurre de karité raffiné cosmétique, pots de 2kg. Qualité blanche, sans odeur. Usage cosmétique et pharmaceutique. Certificat BIO disponible.',
      price: 18000,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 300,
      min_order_quantity: 5,
      status: 'active',
    },
    // Gingembre
    {
      sellerEmail: 'coopcacao@shamar.com',
      name: 'Gingembre séché en poudre',
      description: 'Gingembre séché moulu, sachets de 500g. Origine Côte d\'Ivoire. Usage alimentaire et pharmaceutique. Teneur en gingérol élevée.',
      price: 4500,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 600,
      min_order_quantity: 20,
      status: 'active',
    },
    {
      sellerEmail: 'coopcacao@shamar.com',
      name: 'Gingembre frais sélectionné',
      description: 'Gingembre frais racines, caisses de 20kg. Qualité export, calibre moyen. Conservation optimale. Livraison réfrigérée possible.',
      price: 3500,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 800,
      min_order_quantity: 20,
      status: 'active',
    },
    // Sésame
    {
      sellerEmail: 'cafe@shamar.com',
      name: 'Graines de sésame décortiquées',
      description: 'Graines de sésame décortiquées, sacs de 25kg. Origine Sénégal. Usage boulangerie et huilerie. Taux de pureté 99%.',
      price: 12000,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 500,
      min_order_quantity: 25,
      status: 'active',
    },
    {
      sellerEmail: 'cafe@shamar.com',
      name: 'Huile de sésame pressée',
      description: 'Huile de sésame vierge pressée à froid, bouteilles 750ml. Usage gastronomique et cosmétique. Production artisanale locale.',
      price: 3500,
      currency: 'FCFA',
      category: 'Agro & Matières Premières',
      stock_quantity: 400,
      min_order_quantity: 12,
      status: 'active',
    },

    // ========== INDUSTRIE & ÉQUIPEMENTS - SUITE ==========
    // Sable et gravier
    {
      sellerEmail: 'ciments@shamar.com',
      name: 'Sable de construction lavé',
      description: 'Sable fin lavé pour béton, m3. Granulométrie 0/5mm. Norme NF EN 12620. Livraison camion benne 10m3 minimum.',
      price: 45000,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 0,
      min_order_quantity: 10,
      status: 'active',
    },
    {
      sellerEmail: 'ciments@shamar.com',
      name: 'Gravier 5/15mm',
      description: 'Gravier concassé calibre 5/15mm, m3. Usage béton armé et routes. Livraison camion benne 10m3 minimum. Qualité constante.',
      price: 55000,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 0,
      min_order_quantity: 10,
      status: 'active',
    },
    // Tuyaux PVC
    {
      sellerEmail: 'metal@shamar.com',
      name: 'Tuyaux PVC pression 63mm',
      description: 'Tuyaux PVC pression PN10, diamètre 63mm, longueur 6m. Usage adduction d\'eau potable. Norme ISO 4422. Jonctions et raccords disponibles.',
      price: 12000,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 300,
      min_order_quantity: 10,
      status: 'active',
    },
    {
      sellerEmail: 'metal@shamar.com',
      name: 'Tuyaux PVC évacuation 110mm',
      description: 'Tuyaux PVC évacuation eaux usées, diamètre 110mm, longueur 6m. Usage réseaux d\'assainissement. Norme NF EN 1401. Raccords et manchons inclus.',
      price: 18000,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 250,
      min_order_quantity: 10,
      status: 'active',
    },
    // Briques et parpaings
    {
      sellerEmail: 'ciments@shamar.com',
      name: 'Parpaings creux 20x20x40cm',
      description: 'Parpaings creux en béton, dimensions 20x20x40cm. Usage maçonnerie portante. Résistance à la compression 4MPa. Palettes de 72 pièces.',
      price: 450,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 5000,
      min_order_quantity: 72,
      status: 'active',
    },
    {
      sellerEmail: 'ciments@shamar.com',
      name: 'Briques cuites rouges',
      description: 'Briques en terre cuite, format standard 22x11x6cm. Usage construction traditionnelle. Cuisson optimale, résistance mécanique élevée. Palettes de 400 pièces.',
      price: 150,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 8000,
      min_order_quantity: 400,
      status: 'active',
    },
    // Portes et fenêtres
    {
      sellerEmail: 'metal@shamar.com',
      name: 'Portes métalliques blindées',
      description: 'Portes métalliques blindées standard, dimensions 200x90cm. Tôle 2mm, serrure multipoint. Protection renforcée, finition peinture époxy. Installation incluse.',
      price: 450000,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 50,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'metal@shamar.com',
      name: 'Fenêtres PVC double vitrage',
      description: 'Fenêtres PVC à double vitrage, dimension standard 120x140cm. Ouverture oscillo-battante, vitrage 4/16/4mm. Isolation thermique et phonique. Pose incluse.',
      price: 350000,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 40,
      min_order_quantity: 1,
      status: 'active',
    },
    // Outillage
    {
      sellerEmail: 'metal@shamar.com',
      name: 'Outillage professionnel maçonnerie',
      description: 'Lot d\'outils maçonnerie : truelles, niveaux, marteaux, burins. Qualité professionnelle, acier trempé. Coffret transport inclus.',
      price: 85000,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 80,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'metal@shamar.com',
      name: 'Pinces et outils plomberie',
      description: 'Kit plomberie professionnel : clés, pinces, coupe-tubes, ruban téflon. Acier inoxydable, usage intensif. Coffret métallique.',
      price: 65000,
      currency: 'FCFA',
      category: 'Industrie & Équipements',
      stock_quantity: 60,
      min_order_quantity: 1,
      status: 'active',
    },

    // ========== ÉLECTRONIQUE & HIGH-TECH - SUITE ==========
    // Câbles électriques
    {
      sellerEmail: 'electro@shamar.com',
      name: 'Câbles électriques cuivre 2.5mm²',
      description: 'Câbles électriques souples cuivre, section 2.5mm², rouleau 100m. Norme NFC 15-100. Usage installation résidentielle et tertiaire. Rouleau sous gaine protectrice.',
      price: 85000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 50,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'electro@shamar.com',
      name: 'Tableaux électriques modulaires',
      description: 'Tableaux électriques coffret métallique, 4 à 20 modules. Disjoncteurs différentiels inclus. Installation sur rail DIN. Certificat CE.',
      price: 95000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 30,
      min_order_quantity: 1,
      status: 'active',
    },
    // Éclairage LED
    {
      sellerEmail: 'electro@shamar.com',
      name: 'Ampoules LED 9W E27',
      description: 'Ampoules LED 9W équivalent 60W, culot E27. Blanc chaud et blanc froid disponibles. Durée de vie 25000h. Pack de 10 pièces.',
      price: 12000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 500,
      min_order_quantity: 10,
      status: 'active',
    },
    {
      sellerEmail: 'electro@shamar.com',
      name: 'Panneaux LED 60x60cm',
      description: 'Panneaux LED plafond 60x60cm, 36W, 3500lm. Usage bureaux et commerces. Finition blanche, installation simple. Livraison par 10.',
      price: 35000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 100,
      min_order_quantity: 10,
      status: 'active',
    },
    // Caméras de sécurité
    {
      sellerEmail: 'tech@shamar.com',
      name: 'Caméras IP extérieures',
      description: 'Caméras IP extérieures 1080p, vision nocturne, détection mouvement. WiFi + Ethernet, application mobile incluse. Kit 4 caméras avec enregistreur.',
      price: 450000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 20,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'tech@shamar.com',
      name: 'Système d\'alarme sans fil',
      description: 'Système d\'alarme sans fil complet : centrale, détecteurs, sirène. Communication GSM, application mobile. Installation facile, batterie de secours.',
      price: 250000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 25,
      min_order_quantity: 1,
      status: 'active',
    },
    // Accessoires téléphonie
    {
      sellerEmail: 'electro@shamar.com',
      name: 'Chargeurs USB universels',
      description: 'Chargeurs USB rapide 18W, compatible tous smartphones. Protection surcharge et surchauffe. Câble USB-C inclus. Pack de 5 unités.',
      price: 15000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 300,
      min_order_quantity: 5,
      status: 'active',
    },
    {
      sellerEmail: 'electro@shamar.com',
      name: 'Power banks 20000mAh',
      description: 'Batteries externes 20000mAh, double port USB. Charge rapide, indicateur LED. Compatible tous appareils. Charge complète en 6h.',
      price: 35000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 150,
      min_order_quantity: 3,
      status: 'active',
    },
    // Équipements réseau
    {
      sellerEmail: 'tech@shamar.com',
      name: 'Routeurs WiFi 4G',
      description: 'Routeurs WiFi 4G portables, SIM card incluse. Portée 50m, 32 utilisateurs simultanés. Batterie intégrée 3000mAh. Usage nomade et bureaux.',
      price: 95000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 40,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'tech@shamar.com',
      name: 'Extendeurs WiFi répéteurs',
      description: 'Extendeurs WiFi répéteurs, portée jusqu\'à 300m². Installation simple, application de configuration. Compatible toutes box internet.',
      price: 45000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 60,
      min_order_quantity: 2,
      status: 'active',
    },
    // Équipements solaires
    {
      sellerEmail: 'electro@shamar.com',
      name: 'Batteries solaires lithium 100Ah',
      description: 'Batteries lithium 12V 100Ah pour installations solaires. Cycle de vie 5000 cycles, garantie 5 ans. Protection intégrée, montage flexible.',
      price: 450000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 30,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'electro@shamar.com',
      name: 'Régulateurs solaires PWM 30A',
      description: 'Régulateurs charge solaire PWM 30A, 12/24V. Protection batterie, affichage LCD. Compatible panneaux jusqu\'à 400W. Installation simple.',
      price: 35000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 50,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'electro@shamar.com',
      name: 'Onduleurs solaires 1000W',
      description: 'Onduleurs solaires ondule 1000W 12V, sortie 220V. Usage petits équipements et éclairage. Protection surcharge, indicateurs LED. Garantie 2 ans.',
      price: 125000,
      currency: 'FCFA',
      category: 'Électronique & High-Tech',
      stock_quantity: 40,
      min_order_quantity: 1,
      status: 'active',
    },

    // ========== MODE & TEXTILE - SUITE ==========
    // Vêtements traditionnels
    {
      sellerEmail: 'fashion@shamar.com',
      name: 'Pagnes imprimés assortis',
      description: 'Pagnes imprimés tissu wax, 2 pièces assorties. Largeur 120cm, longueur 2m. Motifs variés, couleurs vives. Usage vêtements et décoration.',
      price: 12000,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 300,
      min_order_quantity: 2,
      status: 'active',
    },
    {
      sellerEmail: 'fashion@shamar.com',
      name: 'Pagnes en tissu bazin',
      description: 'Pagnes en bazin riche, 3 pièces assorties. Qualité premium, finition bordée. Usage cérémonies et événements. Tailles standard.',
      price: 25000,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 200,
      min_order_quantity: 3,
      status: 'active',
    },
    // Chaussures
    {
      sellerEmail: 'fashion@shamar.com',
      name: 'Chaussures cuir artisanales',
      description: 'Chaussures en cuir véritable, fabrication locale. Modèles homme et femme. Semelles résistantes, finition soignée. Tailles 38 à 45.',
      price: 35000,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 150,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'textile@shamar.com',
      name: 'Sandales traditionnelles cuir',
      description: 'Sandales en cuir avec semelles cousues, fabrication artisanale. Design traditionnel, confort optimal. Toutes tailles disponibles.',
      price: 18000,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 200,
      min_order_quantity: 2,
      status: 'active',
    },
    // Accessoires
    {
      sellerEmail: 'fashion@shamar.com',
      name: 'Foulards et écharpes wax',
      description: 'Foulards en tissu wax, dimensions 80x80cm. Motifs authentiques, finition ourlée. Usage quotidien et événements. Couleurs variées.',
      price: 5500,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 400,
      min_order_quantity: 5,
      status: 'active',
    },
    {
      sellerEmail: 'fashion@shamar.com',
      name: 'Chapeaux et casquettes',
      description: 'Chapeaux en tissu wax et casquettes brodées. Protection UV, design moderne. Ajustement universel. Modèles homme et femme.',
      price: 8500,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 250,
      min_order_quantity: 3,
      status: 'active',
    },
    // Cosmétiques naturels
    {
      sellerEmail: 'zena@shamar.com',
      name: 'Savon noir traditionnel',
      description: 'Savon noir à base d\'huile de palme, fabrication artisanale. Usage corporel et ménager. Conditionnement 500g, lot de 12 pièces.',
      price: 4500,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 500,
      min_order_quantity: 12,
      status: 'active',
    },
    {
      sellerEmail: 'zena@shamar.com',
      name: 'Beurre de karité cosmétique',
      description: 'Beurre de karité pur 100%, pots de 250g. Usage hydratation peau et cheveux. Extraction traditionnelle, qualité premium. Certificat BIO.',
      price: 5500,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 400,
      min_order_quantity: 6,
      status: 'active',
    },
    {
      sellerEmail: 'zena@shamar.com',
      name: 'Huiles végétales bio',
      description: 'Huiles végétales biologiques : coco, amande, argan. Flacons 200ml. Usage cosmétique et massage. Production locale, qualité certifiée.',
      price: 8500,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 300,
      min_order_quantity: 3,
      status: 'active',
    },
    // Tissus industriels
    {
      sellerEmail: 'textile@shamar.com',
      name: 'Tissus coton imprimé',
      description: 'Tissus coton 100% imprimés, largeur 150cm. Motifs variés, résistance lavage. Usage vêtements et ameublement. Rouleaux de 50m.',
      price: 6500,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 150,
      min_order_quantity: 10,
      status: 'active',
    },
    {
      sellerEmail: 'textile@shamar.com',
      name: 'Tissus lin mélangé',
      description: 'Tissus lin mélangé coton, largeur 140cm. Texture naturelle, usage vêtements et draps. Rouleaux de 30m. Couleurs unies disponibles.',
      price: 12000,
      currency: 'FCFA',
      category: 'Mode & Textile',
      stock_quantity: 100,
      min_order_quantity: 5,
      status: 'active',
    },

    // ========== TOURISME & SERVICES ==========
    {
      sellerEmail: 'africatrade@shamar.com',
      name: 'Services de restauration événementielle',
      description: 'Catering pour événements : mariages, séminaires, cocktails. Cuisine locale et internationale. Service complet avec personnel. Minimum 50 personnes.',
      price: 15000,
      currency: 'FCFA',
      category: 'Tourisme & Services',
      stock_quantity: 0,
      min_order_quantity: 50,
      status: 'active',
    },
    {
      sellerEmail: 'sodex@shamar.com',
      name: 'Location matériel événementiel',
      description: 'Location mobilier événementiel : tables, chaises, tentes, sonorisation. Installation et désinstallation incluses. Tarif jour ou semaine.',
      price: 50000,
      currency: 'FCFA',
      category: 'Tourisme & Services',
      stock_quantity: 0,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'sodex@shamar.com',
      name: 'Services traduction FR/EN',
      description: 'Services de traduction professionnelle français-anglais. Documents commerciaux, contrats, communications. Traducteurs certifiés. Tarif à la page.',
      price: 8500,
      currency: 'FCFA',
      category: 'Tourisme & Services',
      stock_quantity: 0,
      min_order_quantity: 1,
      status: 'active',
    },

    // ========== IMPORT / EXPORT - SUITE ==========
    {
      sellerEmail: 'sourcingchina@shamar.com',
      name: 'Équipements de cuisine Chine',
      description: 'Sourcing équipements de cuisine professionnelle : casseroles, poêles, ustensiles. Inox 304, qualité export. MOQ 200 pièces. Inspection qualité.',
      price: 850,
      currency: 'USD',
      category: 'Import / Export',
      stock_quantity: 0,
      min_order_quantity: 200,
      status: 'active',
    },
    {
      sellerEmail: 'sourcingchina@shamar.com',
      name: 'Textiles et vêtements Chine',
      description: 'Sourcing vêtements et textiles gros volume : t-shirts, pantalons, textiles maison. Qualité contrôlée, prix compétitifs. Container complet. FOB Guangzhou.',
      price: 35000,
      currency: 'USD',
      category: 'Import / Export',
      stock_quantity: 0,
      min_order_quantity: 1000,
      status: 'active',
    },
    {
      sellerEmail: 'importexport@shamar.com',
      name: 'Services douane et transit',
      description: 'Services douaniers complets : déclaration, transit, dédouanement. Ports Afrique et Europe. Expertise réglementaire, suivi complet. Tarif selon tonnage.',
      price: 350,
      currency: 'EUR',
      category: 'Import / Export',
      stock_quantity: 0,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'importexport@shamar.com',
      name: 'Transport routier longue distance',
      description: 'Transport routier Afrique de l\'Ouest : CI, SN, BJ, TG, NG. Camions 20T et 30T. Assurances incluses, suivi GPS. Tarif au km ou forfait.',
      price: 450,
      currency: 'EUR',
      category: 'Import / Export',
      stock_quantity: 0,
      min_order_quantity: 1,
      status: 'active',
    },
    {
      sellerEmail: 'africatrade@shamar.com',
      name: 'Stockage et entreposage',
      description: 'Services d\'entreposage : stockage sécurisé, gestion inventaire, préparation commandes. Ports Abidjan et Dakar. Tarif m²/mois.',
      price: 15000,
      currency: 'FCFA',
      category: 'Import / Export',
      stock_quantity: 0,
      min_order_quantity: 10,
      status: 'active',
    },
  ],
};
